language: node_js
sudo: false
node_js:
  - "4"
  - "5"
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database w3gram_test;' -U postgres
env: DATABASE_URL=postgresql://postgres@localhost/w3gram_test
